# ======================================================
# EDSE Configuration File
# ======================================================

alpha: 0.10
seed: 42

vocab_path: "data/vocab.txt"

punctuation:
  - "،"
  - "؟"
  - "."
  - "!"
  - ":"
  - ";"
  - "—"
  - "-"
  - "…"
  - "«"
  - "»"

min_len_for_char_ops: 2

